#!/usr/bin/env python

import sys, os
from optparse import OptionParser

from lazygal import Album

usage = "usage: %prog [options] albumdir"
parser = OptionParser(usage=usage)
parser.add_option("-o", "--output-directory",
                  action="store", type="string",
                  dest="dest_dir", default=".",
                  help="Directory where web pages, slides and thumbs will be written (default is current directory).")
parser.add_option("-t", "--theme",
                  action="store", type="string",
                  dest="theme", default="default",
                  help="Theme name (looked up in them directory) or theme full path.")
parser.add_option("", "--clean-destination",
                  action="store_true",
                  dest="clean_dest", default=False,
                  help="Clean destination directory of files that should not be there.")
(options, args) = parser.parse_args()

if len(args) != 1:
    parser.print_help()
    sys.exit("Bad command line.")

source_dir = args[0]
if not os.path.isdir(source_dir):
    sys.exit("Directory " + source_dir + " does not exist.")

album = Album(source_dir,
              (150, 113),
              [('small', (800, 600)), ('medium', (1024, 768))])
album.set_theme(options.theme)
album.generate(options.dest_dir, options.clean_dest)


# vim: ts=4 sw=4 expandtab
