<!DOCTYPE html
     PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
     "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>%(title)s</title>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <link rel="stylesheet" type="text/css" media="screen,projection" title="Original" href="%(rel_root)sshared/style.css" />
</head>

<body>

<h1>%(title)s</h1>

<p><a href="..">Parent</a></p>

<ul id="subgal_links">
  %(subgals)s
</ul>

<div id="image_links">
  %(images)s
</div>

<div id="footer">Generated by <a href="http://sousmonlit.dyndns.org/~niol/playa/oss:lazygal">lazygal</a>.</div>

</body>

</html>
